In [2]:
#📦 Core Libraries
import os
import cv2 as cv
import numpy as np
import pandas as pd

#🧠 Machine Learning Libraries                    
from sklearn.svm import SVC
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from dicionario_SIFT import artefatos_sift, load_images_from_folder

# Grupos de features

In [3]:
lista_descritores = np.load('lista_sift.npz')["lista_descritores"]
lista_descritores = pd.DataFrame(lista_descritores)

In [4]:
kmeans = KMeans(n_clusters=10, random_state=0).fit(lista_descritores)
print(kmeans.cluster_centers_)

[[20.353642 16.018438 12.906467 ...  5.746704  6.352611 21.948318]
 [65.084885 38.821777 13.879278 ...  9.974244  7.801259 14.296763]
 [23.682995 14.093749 10.516691 ... 11.684764  8.928069 19.286013]
 ...
 [30.782282 34.829533 30.68178  ... 12.377581 15.713222 23.603952]
 [18.86336  17.055082 17.771997 ... 18.817049 18.877087 21.782925]
 [33.59326  33.65289  28.649101 ... 10.339494 10.905724 17.51773 ]]


In [5]:
dic_imges = load_images_from_folder(r'datasets')
sift = artefatos_sift(dic_imges)
list_descritores = sift[0]
dic_features = sift[1]

In [6]:
dic_features.keys()

dict_keys(['Apes', 'Owls'])

In [7]:
dic_histogram = {}
features = []
labels_list = []
for i, _ in dic_features.items():
    
    for index, img in enumerate(_):
        lista_hist = []
        descritor = dic_features[i][index]
        labels = kmeans.predict(descritor)
        histograma, _ = np.histogram(labels, bins = np.arange(kmeans.n_clusters + 1))
        lista_hist.append(histograma)
        features.append(histograma)
        labels_list.append(0 if i == "Apes" else 1)


    dic_histogram[i] = lista_hist
print(dic_histogram)

{'Apes': [array([144, 130, 223, 174,  96, 166, 179, 196, 210, 213])], 'Owls': [array([136, 149, 258, 361, 282, 147, 419, 145, 131, 128])]}


In [9]:
dic_histogram.keys()

dict_keys(['Apes', 'Owls'])

# Treinamento SVM

In [11]:
X_train, X_test, y_train, y_test = train_test_split(features, labels_list, test_size=0.2, random_state=42)

In [12]:
model = SVC()
model.fit(X_train, y_train)

,C,1.0
,kernel,'rbf'
,degree,3
,gamma,'scale'
,coef0,0.0
,shrinking,True
,probability,False
,tol,0.001
,cache_size,200
,class_weight,None
,verbose,False


In [13]:
y_predict = model.predict(X_test)

In [14]:
y_predict

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0])

In [15]:
y_test

[0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0]

In [16]:
image_test = cv.imread('macaco_brabo.jpg')
print(image_test)
sift = cv.SIFT_create()
keypoints, descriptors = sift.detectAndCompute(image_test, None)
labels = kmeans.predict(descriptors)
histograma, _ = np.histogram(labels, bins = np.arange(kmeans.n_clusters + 1))

None


error: OpenCV(4.12.0) D:\a\opencv-python\opencv-python\opencv\modules\features2d\src\sift.dispatch.cpp:512: error: (-5:Bad argument) image is empty or has incorrect depth (!=CV_8U) in function 'cv::SIFT_Impl::detectAndCompute'


In [ ]:
model.predict([histograma])

array([0])