In [100]:
import numpy as np
import pandas as pd                     
from sklearn.svm import SVC
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
import cv2 as cv
import os
from dicionario_SIFT import artefatos_sift, load_images_from_folder

In [4]:
lista_descritores = np.load('lista_sift.npz')["lista_descritores"]
lista_descritores = pd.DataFrame(lista_descritores)

In [6]:
lista_descritores

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,...,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,12.0,6.0,10.0,47.0,16.0,1.0,47.0,12.0,6.0,4.0,8.0,31.0,21.0,117.0,43.0,7.0,24.0,13.0,10.0,14.0,65.0,89.0,0.0,1.0,2.0,0.0,0.0,10.0,2.0,0.0,...,6.0,30.0,120.0,87.0,61.0,37.0,4.0,1.0,55.0,73.0,10.0,0.0,0.0,0.0,1.0,7.0,120.0,74.0,24.0,7.0,1.0,26.0,43.0,28.0,1.0,1.0,38.0,30.0,54.0,120.0,53.0,3.0,1.0,9.0,9.0,19.0,97.0,88.0,8.0,0.0
1,91.0,26.0,9.0,43.0,42.0,7.0,6.0,12.0,1.0,8.0,39.0,61.0,63.0,11.0,1.0,1.0,8.0,6.0,17.0,56.0,72.0,51.0,47.0,9.0,34.0,27.0,12.0,8.0,1.0,16.0,51.0,15.0,35.0,61.0,82.0,80.0,32.0,1.0,1.0,4.0,...,36.0,73.0,114.0,25.0,19.0,23.0,3.0,15.0,21.0,3.0,5.0,8.0,7.0,8.0,32.0,61.0,33.0,6.0,2.0,6.0,8.0,17.0,34.0,63.0,13.0,6.0,14.0,31.0,24.0,22.0,38.0,51.0,46.0,17.0,16.0,10.0,2.0,1.0,19.0,114.0
2,51.0,17.0,2.0,3.0,10.0,17.0,18.0,25.0,10.0,5.0,1.0,3.0,35.0,76.0,35.0,4.0,47.0,75.0,9.0,0.0,1.0,18.0,63.0,32.0,35.0,81.0,43.0,9.0,5.0,5.0,14.0,15.0,67.0,28.0,2.0,1.0,13.0,24.0,16.0,67.0,...,12.0,19.0,16.0,114.0,88.0,7.0,5.0,6.0,30.0,25.0,35.0,25.0,1.0,1.0,17.0,40.0,26.0,68.0,114.0,16.0,0.0,1.0,8.0,7.0,4.0,27.0,114.0,51.0,28.0,3.0,10.0,7.0,4.0,7.0,13.0,35.0,28.0,20.0,13.0,3.0
3,14.0,5.0,8.0,27.0,15.0,5.0,9.0,12.0,42.0,16.0,24.0,56.0,14.0,2.0,2.0,17.0,58.0,11.0,8.0,2.0,6.0,44.0,48.0,62.0,21.0,2.0,2.0,4.0,16.0,35.0,58.0,78.0,10.0,5.0,13.0,20.0,21.0,21.0,36.0,37.0,...,19.0,9.0,8.0,53.0,124.0,41.0,16.0,21.0,2.0,30.0,27.0,5.0,33.0,28.0,7.0,1.0,74.0,124.0,33.0,2.0,0.0,1.0,6.0,14.0,96.0,124.0,2.0,3.0,31.0,32.0,8.0,32.0,9.0,12.0,13.0,8.0,53.0,76.0,57.0,51.0
4,17.0,14.0,15.0,19.0,35.0,3.0,1.0,8.0,28.0,11.0,3.0,18.0,100.0,19.0,1.0,6.0,81.0,17.0,1.0,1.0,18.0,22.0,10.0,32.0,2.0,10.0,2.0,3.0,33.0,46.0,6.0,1.0,2.0,6.0,15.0,21.0,21.0,36.0,9.0,1.0,...,18.0,27.0,11.0,9.0,127.0,127.0,0.0,1.0,5.0,39.0,79.0,31.0,8.0,3.0,4.0,4.0,28.0,123.0,26.0,13.0,11.0,8.0,8.0,6.0,109.0,125.0,12.0,22.0,27.0,6.0,3.0,5.0,55.0,44.0,3.0,2.0,105.0,78.0,3.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61101,36.0,6.0,1.0,9.0,13.0,1.0,0.0,5.0,126.0,3.0,0.0,0.0,0.0,4.0,24.0,93.0,104.0,0.0,0.0,0.0,0.0,23.0,61.0,84.0,145.0,0.0,0.0,0.0,18.0,17.0,4.0,66.0,67.0,14.0,2.0,9.0,3.0,0.0,0.0,1.0,...,119.0,1.0,0.0,2.0,18.0,1.0,3.0,61.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,89.0,3.0,0.0,0.0,0.0,0.0,0.0,16.0,145.0,2.0,0.0,0.0,0.0,0.0,2.0,69.0,34.0,0.0,0.0,4.0,20.0,1.0,1.0,42.0
61102,35.0,108.0,12.0,18.0,60.0,8.0,0.0,0.0,158.0,125.0,7.0,2.0,2.0,1.0,5.0,15.0,20.0,3.0,5.0,6.0,0.0,0.0,7.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67.0,29.0,3.0,18.0,111.0,15.0,0.0,0.0,...,0.0,1.0,4.0,1.0,3.0,2.0,1.0,1.0,59.0,0.0,0.0,0.0,53.0,134.0,23.0,39.0,165.0,6.0,0.0,0.0,29.0,35.0,6.0,36.0,54.0,5.0,13.0,21.0,151.0,38.0,2.0,10.0,3.0,8.0,15.0,7.0,14.0,2.0,0.0,1.0
61103,58.0,26.0,2.0,0.0,0.0,1.0,4.0,12.0,24.0,38.0,2.0,0.0,0.0,12.0,45.0,17.0,26.0,3.0,0.0,0.0,0.0,2.0,90.0,142.0,2.0,6.0,4.0,0.0,9.0,56.0,135.0,70.0,10.0,29.0,3.0,0.0,0.0,0.0,1.0,7.0,...,61.0,20.0,8.0,118.0,142.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,4.0,5.0,50.0,61.0,20.0,6.0,1.0,0.0,3.0,12.0,7.0,28.0,32.0,81.0,97.0,19.0,6.0,1.0
61104,123.0,65.0,0.0,1.0,9.0,5.0,0.0,0.0,125.0,131.0,1.0,0.0,0.0,1.0,3.0,5.0,8.0,131.0,38.0,0.0,0.0,1.0,3.0,1.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,131.0,39.0,0.0,0.0,37.0,13.0,1.0,15.0,...,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,131.0,0.0,0.0,3.0,29.0,5.0,9.0,131.0,55.0,18.0,3.0,18.0,80.0,39.0,38.0,109.0,59.0,74.0,4.0,7.0,9.0,2.0,1.0,2.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0


In [ ]:
kmeans = KMeans(n_clusters=10, random_state=0).fit(lista_descritores)
print(kmeans.cluster_centers_)

[[20.353642  16.018438  12.906467  ...  5.746705   6.3526106 21.948318 ]
 [65.084885  38.821777  13.879278  ...  9.974243   7.801259  14.296762 ]
 [23.682993  14.093749  10.516691  ... 11.684763   8.928068  19.286013 ]
 ...
 [30.782282  34.829533  30.68178   ... 12.37758   15.713222  23.603952 ]
 [18.86336   17.05508   17.771997  ... 18.817049  18.877087  21.782925 ]
 [33.59326   33.65289   28.649101  ... 10.339493  10.905724  17.51773  ]]


In [25]:
dic_imges = load_images_from_folder(r'datasets')
sift = artefatos_sift(dic_imges)
list_descritores = sift[0]
dic_features = sift[1]

In [45]:
dic_features.keys()

dict_keys(['Apes', 'Owls'])

In [93]:
dic_histogram = {}
features = []
labels_list = []
for i, _ in dic_features.items():
    
    for index, img in enumerate(_):
        lista_hist = []
        descritor = dic_features[i][index]
        labels = kmeans.predict(descritor)
        histograma, _ = np.histogram(labels, bins = np.arange(kmeans.n_clusters + 1))
        lista_hist.append(histograma)
        features.append(histograma)
        labels_list.append(0 if i == "Apes" else 1)


    dic_histogram[i] = lista_hist
print(dic_histogram)

{'Apes': [array([144, 130, 223, 174,  96, 166, 179, 196, 210, 213], dtype=int64)], 'Owls': [array([136, 149, 258, 361, 282, 147, 419, 145, 131, 128], dtype=int64)]}


In [94]:
len(labels_list)

50

In [97]:
dic_histogram.keys()

dict_keys(['Apes', 'Owls'])

In [90]:
for i in features:
    print(len(i))

10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10


In [102]:
X_train, X_test, y_train, y_test = train_test_split(features, labels_list, test_size=0.2, random_state=42)

In [103]:
model = SVC()
model.fit(X_train, y_train)

SVC()

In [104]:
y_predict = model.predict(X_test)

In [105]:
y_predict

array([0, 1, 0, 1, 0, 1, 0, 0, 1, 0])

In [106]:
y_test

[0, 1, 0, 1, 0, 1, 0, 0, 1, 0]

In [120]:
image_test = cv.imread('macaco_brabo.jpg')
print(image_test)
sift = cv.SIFT_create()
keypoints, descriptors = sift.detectAndCompute(image_test, None)
labels = kmeans.predict(descriptors)
histograma, _ = np.histogram(labels, bins = np.arange(kmeans.n_clusters + 1))

[[[10  4  5]
  [12  4  5]
  [12  4  5]
  ...
  [ 9  4  5]
  [ 9  4  5]
  [ 9  4  5]]

 [[12  4  5]
  [12  4  5]
  [12  4  5]
  ...
  [ 9  4  5]
  [ 9  4  5]
  [ 9  4  5]]

 [[12  4  5]
  [12  4  5]
  [12  4  5]
  ...
  [ 9  4  5]
  [ 9  4  5]
  [ 9  4  5]]

 ...

 [[ 9  4  5]
  [ 9  4  5]
  [ 9  4  5]
  ...
  [ 9  4  5]
  [ 9  4  5]
  [ 9  4  5]]

 [[ 9  4  5]
  [ 9  4  5]
  [ 9  4  5]
  ...
  [ 9  4  5]
  [ 9  4  5]
  [ 9  4  5]]

 [[ 9  4  5]
  [ 9  4  5]
  [ 9  4  5]
  ...
  [ 9  4  5]
  [ 9  4  5]
  [ 9  4  5]]]


In [121]:
model.predict([histograma])

array([0])